apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: meldeplikt.v1
  namespace: aap
  labels:
    team: aap
  annotations:
    # Revurder om topic skal slettes sammen med kubernetesressursen når topic opprettes i prod
    kafka.nais.io/removeDataWhenResourceIsDeleted: "true"
    githubUrl: "https://github.com/navikt/aap-meldeplikt"
spec:
  pool: {{kafka-pool}}
  config:
    cleanupPolicy: compact,delete
    partitions: 12
    retentionHours: 1
  acl:
    - team: aap
      application: meldeplikt
      access: readwrite
    - team: aap
      application: utbetaling
      access: read