apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: meldeplikt.v1
  namespace: aap
  labels:
    team: aap
    sub: vedtak
  annotations:
    kafka.nais.io/removeDataWhenResourceIsDeleted: "{{kafka.permanent-delete-topics}}"
    github.url: https://github.com/navikt/aap-meldeplikt
spec:
  pool: {{kafka.pool}}
  config:
    cleanupPolicy: compact,delete
    partitions: 12
    retentionHours: 168
  acl:
    - team: aap
      application: meldeplikt
      access: readwrite
    - team: aap
      application: utbetaling
      access: readwrite
    - team: aap
      application: sink
      access: read
  {{#each kafka.acl.dev as |dev|}}
    - team: "{{dev.team}}"
      application: "{{dev.application}}"
      access: "{{dev.access}}"
  {{/each}}
