/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package no.nav.aap

import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

class AppTest {

    @Test
    fun hello() {
        assertTrue(true)
    }
}
